project:
  type: website
  output-dir: docs
  preview:
    port: 3333

website:
  title: "MUSA 550 Final Project"
  page-footer:
    left: "christineguo6@gmail.com"
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."

  sidebar:
    logo: "images/ST_DISTRIBUTION.jpg"
    pinned: true
    align: center
    tools:
      - icon: globe
        href: https://github.com/ZoeyGuo709/Final
        text: "Project Website"
      - icon: github
        href: https://github.com/ShengaoYi
        text: "Shengao Yi GitHub"
      - icon: github
        href: https://github.com/ZoeyGuo709
        text: "Ziyi Guo Github"
    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Welcome
      - about.qmd
      - section: analysis/index.qmd
        contents:
          - analysis/1-currentData.ipynb 
          - analysis/2-static-images.ipynb
          - analysis/3-altair-hvplot.ipynb
          - analysis/4-folium.ipynb

format:
  html:
    highlight-style: solarized
    theme: cosmo
    css: styles.css
    code-copy: true
    code-overflow: wrap
    toc: true
