---
title: "MUSA 550: Final Project"
subtitle: "Exploring the relationship between heat stress around bus stops and urban environment: A case study of Philadelphia"
---

## Welcome!

This web is demonstrating our research on heat stress around bus stops, and how this heat strees can be related to what 

The Urban Heat Island (UHI) effect poses significant challenges to public transit users, especially those waiting at bus stops, where prolonged exposure to extreme heat can result in serious health risks. Despite growing awareness of these dangers, there remains a lack of research examining hyperlocal heat stress levels around bus stops and their interactions with surrounding urban environments. To address this gap, this study leverages Universal Thermal Climate Index (UTCI) data across Philadelphia to analyze heat stress variations in the immediate vicinity of bus stops. Using a Random Forest (RF) model, we investigate the nonlinear relationships and threshold effects between heat stress, socioeconomic characteristics, and built environment factors. The findings reveal substantial spatio-temporal variations in heat stress, with consistently elevated levels during midday hours across the city. Notably, bus stops in neighborhoods with higher poverty rates experience greater heat stress, while those in wealthier areas, as indicated by higher median household values, show comparatively lower levels of heat stress. These results underscore the urgent need for targeted and equitable heat mitigation strategies to protect vulnerable populations in high-risk areas.
